// Company
export const ADD_COMPANY = 'ADD_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const FILTER_COMPANY = 'FILTER_COMPANY';
export const CLEAR_FILTER_COMPANY = 'CLEAR_FILTER_COMPANY';

// Company auth
export const COM_REGISTER_SUCCESS = 'COM_REGISTER_SUCCESS';
export const COM_REGISTER_FAIL = 'COM_REGISTER_FAIL';
export const USER_LOADED = 'USE_LOADED';
export const COM_AUTH_ERROR = 'COM_AUTH_ERROR';
export const COM_LOGIN_SUCCESS = 'COM_LOGIN_SUCCESS';
export const COM_LOGIN_FAIL = 'COM_LOGIN_FAIL';
export const COM_LOGOUT = 'COM_LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
