// Company
export const ADD_COMPANY = 'ADD_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const FILTER_COMPANY = 'FILTER_COMPANY';
export const CLEAR_FILTER_COMPANY = 'CLEAR_FILTER_COMPANY';

// Company auth
export const COM_REGISTER_SUCCESS = 'COM_REGISTER_SUCCESS';
export const COM_REGISTER_FAIL = 'COM_REGISTER_FAIL';
export const COM_USER_LOADED = 'COM_LOADED';
export const COM_AUTH_ERROR = 'COM_AUTH_ERROR';
export const COM_LOGIN_SUCCESS = 'COM_LOGIN_SUCCESS';
export const COM_LOGIN_FAIL = 'COM_LOGIN_FAIL';
export const COM_LOGOUT = 'COM_LOGOUT';
export const COM_CLEAR_ERRORS = 'COM_CLEAR_ERRORS';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// User
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FILTER_USER = 'FILTER_USER';
export const CLEAR_FILTER_USER = 'CLEAR_FILTER_COMPANY';
// User auth
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_USER_LOADED = 'USER_LOADED';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CLEAR_ERRORS = 'USER_CLEAR_ERRORS';
export const USER_ERROR = 'USER_ERROR';
